# docker-compose.dev.yml（開発用）
services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports: ["6333:6333"]
    volumes:
      - ./data/vectorstore/qdrant:/qdrant/storage

  api:
    build: .
    env_file: .env
    environment:
      QDRANT_URL: http://qdrant:6333
    depends_on: [qdrant]
    ports: ["8000:8000"]
    volumes:
      - ./:/app            # ← ソースをそのままマウント
    command: >
      sh -c "
      until wget -qO- http://qdrant:6333/ >/dev/null 2>&1; do
        echo '[api] waiting qdrant...'; sleep 1;
      done &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
      "
