# docker-compose.yml
services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    container_name: qdrant
    ports:
      - "6333:6333"
    # DATA_PROFILE=small | full でマウント切替
    volumes:
      - ./data/${DATA_PROFILE:-small}/qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/"]
      interval: 5s
      timeout: 2s
      retries: 20

  api:
    build: .
    container_name: fashion-rag-api
    env_file: .env        # ← 配布しない。各自で作成
    environment:
      # composeの変数展開でプロファイルを共有
      DATA_PROFILE: ${DATA_PROFILE:-small}
      QDRANT_URL: http://qdrant:6333
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-small}
      ALPHA: ${ALPHA:-0.6}
      TOP_K: ${TOP_K:-5}
      # 少量/全量で ingest 先ファイルを切替
      INGEST_JSONL: /app/data/${DATA_PROFILE:-small}/embeddings.jsonl
    depends_on:
      qdrant:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python -m scripts.ingest --jsonl ${INGEST_JSONL} --skip-if-exists &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
